const schema = {
  type: 'object',
  properties: {
    first_name: {
      type: 'string',
      minLength: 1,
      pattern: '^(?!\\s*$).+',
    },
    last_name: { type: 'string' },
    email: { type: 'string', format: 'email', minLength: 5 },
    password: { type: 'string', minLength: 5, maxLength: 20, pattern: '^(?!\\s*$).+' },
    mobile: {
      type: 'string',
      pattern: '^([0|+[0-9]{1,5})?([7-9][0-9]{9})$',
    },
    address: { type: 'string', minLength: 5, pattern: '^(?!\\s*$).+' },
    city: { type: 'string', minLength: 1 },
    pin_code: { type: 'string', minLength: 6 },
    country: { type: 'string', minLength: 1, pattern: '^(?!\\s*$).+' },
    gst_legal_entity_name: { type: 'string', minLength: 1, pattern: '^(?!\\s*$).+' },
    gst_business_address: { type: 'string', minLength: 1, pattern: '^(?!\\s*$).+' },
    gst_city_code: { type: 'string', minLength: 1, pattern: '^(?!\\s*$).+' },
    gst_no: { type: 'string', minLength: 8, pattern: '^(?!\\s*$).+' },
    name_as_per_pan: { type: 'string', minLength: 1, pattern: '^(?!\\s*$).+' },
    pan_no: {
      type: 'string',
      pattern: '^[A-Z]{5}\\d{4}[A-Z]$',
    },
    pan_date_of_incorporation: { type: 'string' },
    subscriber_id: { type: 'string', minLength: 1, pattern: '^(?!\\s*$).+' },
    // site_url: { type: "string", minLength: 1, pattern: "^(?!\\s*$).+" },
    ukid: { type: 'string', minLength: 1, pattern: '^(?!\\s*$).+' },
    company_address: { type: 'string', minLength: 5, pattern: '^(?!\\s*$).+' },
    business_registration_no: { type: 'string', minLength: 1 },
    bank_account_no: { type: 'string', minLength: 1 },
    bank_ifsc_code: { type: 'string', minLength: 1 },
    np_rsp_url: { type: 'string', minLength: 1 },
    sign_public_key: { type: 'string', minLength: 1, pattern: '^(?!\\s*$).+' },
    encr_public_key: { type: 'string', minLength: 1, pattern: '^(?!\\s*$).+' },
    subscriber_type: { type: 'string', enum: ['BPP', 'BAP', 'BG'] },
    ttl: { type: 'string', minLength: 1 },
  },
  errorMessage: {
    properties: {
      first_name: 'first_name should be valid, current value is ${/first_name}',
      last_name: 'last_name should be valid, current value is ${/last_name}',
      email: 'email should be valid, current value is ${/email}',
      password: 'password should be valid, current value is ${/password}',
      mobile: 'mobile should be valid, current value is ${/mobile}',
      address: 'address should be valid, current value is ${/address}',
      city: 'city should be valid, current value is ${/city}',
      pin_code: 'pin_code should be valid, current value is ${/pin_code}',
      country: 'country should be valid, current value is ${/country}',
      gst_legal_entity_name: 'gst_legal_entity_name should be valid, current value is ${/gst_legal_entity_name}',
      gst_business_address: 'gst_business_address should be valid, current value is ${/gst_business_address}',
      gst_city_code: 'gst_city_code should be valid, current value is ${/gst_city_code}',
      gst_no: 'gst_no should be valid, current value is ${/gst_no}',
      name_as_per_pan: 'name_as_per_pan should be valid, current value is ${/name_as_per_pan}',
      pan_no: 'pan_no should be valid, current value is ${/pan_no}',
      pan_date_of_incorporation:
        'pan_date_of_incorporation should be valid, current value is ${/pan_date_of_incorporation}',
      subscriber_id: 'subscriber_id should be valid, current value is ${/subscriber_id}',
      site_url: 'site_url should be valid, current value is ${/site_url}',
      ukid: 'ukid should be valid, current value is ${/ukid}',
      subscriber_type: 'subscriber_type should be valid i.e. from (BPP, BAP, BG), current value is ${/subscriber_type}',
      company_address: 'company_address should be valid, current value is ${/company_address}',
      business_registration_no:
        'business_registration_no should be valid, current value is ${/business_registration_no}',
      bank_account_no: 'bank_account_no should be valid, current value is ${/bank_account_no}',
      bank_ifsc_code: 'bank_ifsc_code should be valid, current value is ${/bank_ifsc_code}',
      np_rsp_url: 'np_rsp_url should be valid, current value is ${/np_rsp_url}',
      sign_public_key: 'sign_public_key should be valid, current value is ${/sign_public_key}',
      encr_public_key: 'encr_public_key should be valid, current value is ${/encr_public_key}',
      ttl: 'ttl should be valid, current value is ${/ttl}',
    },
  },
  required: [
    'first_name',
    'email',
    'mobile',
    'address',
    'city',
    'pin_code',
    'country',
    'gst_legal_entity_name',
    'gst_business_address',
    'gst_city_code',
    'gst_no',
    'name_as_per_pan',
    'pan_no',
    'pan_date_of_incorporation',
    'subscriber_id',
    'subscriber_type',
    'company_address',
    // "business_registration_no",
    'bank_account_no',
    'bank_ifsc_code',
    'np_rsp_url',
    'sign_public_key',
    'encr_public_key',
  ],
}

export default schema
