version: '3'
services:
  nodeapp:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    restart: always

networks:
  app-network:
    external: true

