name: BE Staging Deployment

on:
  push:
    branches:
      - stage
    paths:
      - 'blog-app/backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - uses: actions/checkout@v2

      # Step 2: Extract Branch Name
      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      # Step 3: Connect to EC2 and Deploy
      - name: Build and run Docker on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          command_timeout: 30m
          script: |
            set -e
            docker system prune -a -f
            cd blog-app/backend/
            git pull || { echo "Failed to fetch from the repository"; exit 1; }
            git checkout origin/${{ env.branch }}
            git switch -C ${{ env.branch }}
            docker-compose -f docker-compose.yml up -d --build
            docker-compose -f docker-compose.yml restart
